# Changes here will be overwritten by Copier
_commit: '6957226'
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: dev@dau.dev
github: dau-dev
project_description: Utilities for dau
project_name: dau utils
python_version_primary: '3.11'
team: the dau authors
